---
project:
  owner: aws-redhat-partnerteam@amazon.com
  name: cfn-ps-red-hat-rhel-with-ha
  regions:
    - us-east-1
  s3_regional_buckets: true
tests:
  default:
    template: ./templates/main.template.yaml
    parameters:
      NodeOS: "RHELHA88HVM"
      KeyPairName: "$[taskcat_getkeypair]"
      AvailabilityZones: "$[taskcat_getaz_3]"
      NumberOfAZs: "3"
      QSS3KeyPrefix: "cfn-ps-red-hat-rhel-with-ha/"
      QSS3BucketName: '$[taskcat_autobucket]'
      QSS3BucketRegion: "$[taskcat_current_region]"
      ClusterPassword: "$[taskcat_genpass_8A]"
      RemoteAccessCIDR: "0.0.0.0/0"