---
AWSTemplateFormatVersion: 2010-09-09
Description: This template sets up RHEL with HA in Node 3 of the cluster. (qs-1s2qufol1)
Parameters:
  KeyPairName:
    ConstraintDescription: "Name of an existing EC2 KeyPair."
    Type: "AWS::EC2::KeyPair::KeyName"
  InstanceType:
    Default: t2.medium
    Description: "EC2 instance type"
    Type: String
  SubnetId:
    Description: "Identifer of subnet the instance resides in"
    Type: AWS::EC2::Subnet::Id
  ImageId:
    Description: "ID of AMI used to launch instance"
    Type: AWS::EC2::Image::Id
  SecurityGroupId:
    Description: "ID of Security Group for cluster communication"
    Type: AWS::EC2::SecurityGroup::Id
  ClusterPassword:
    Description: Password used for the user HACluster in the RHEL HA setup
    Type: String
    NoEcho: true
  BucketName:
    Description: Name of bucket that will contain the hostnames
    Type: String
  ClusterRole:
    Description: IAM Role for access to S3 Bucket
    Type: String
  ClusterProfile:
    Type: String
  FloatingIPAddress:
    Type: String
  RouteTableId:
    Type: String
Resources:
  RHELwithHAInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairName
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref ClusterProfile
      SubnetId: !Ref SubnetId
      ImageId: !Ref ImageId
      SecurityGroupIds:
        - !Ref SecurityGroupId
