---
AWSTemplateFormatVersion: 2010-09-09
Description: This template sets up RHEL with HA in Node 2 of the cluster.
Parameters:
  KeyPairName:
    ConstraintDescription: "Name of an existing EC2 KeyPair."
    Type: "AWS::EC2::KeyPair::KeyName"
  InstanceType:
    Default: t2.medium
    Description: "EC2 instance type"
    Type: String
  SubnetId:
    Description: "Identifer of subnet the instance resides in"
    Type: AWS::EC2::Subnet::Id
  ImageId:
    Description: "ID of AMI used to launch instance"
    Type: String
Resources:
  RHELwithHAInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairName
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      ImageId: !Ref ImageId
