---
AWSTemplateFormatVersion: 2010-09-09
Description: This template sets up RHEL with HA in Node 3 of the cluster. (qs-1s2qufol1)
Parameters:
  KeyPairName:
    ConstraintDescription: "Name of an existing EC2 KeyPair."
    Type: "AWS::EC2::KeyPair::KeyName"
  InstanceType:
    Default: t2.medium
    Description: "EC2 instance type"
    Type: String
  SubnetId:
    Description: "Identifer of subnet the instance resides in"
    Type: AWS::EC2::Subnet::Id
  ImageId:
    Description: "ID of AMI used to launch instance"
    Type: AWS::EC2::Image::Id
  SecurityGroupId:
    Description: "ID of Security Group for cluster communication"
    Type: AWS::EC2::SecurityGroup::Id
  # ClusterPassword:
  #   Description: Password used for the user HACluster in the RHEL HA setup
  #   Type: String
  #   NoEcho: true
  # BucketName:
  #   Description: Name of bucket that will contain the hostnames
  #   Type: String
  # ClusterRole:
  #   Description: IAM Role for access to S3 Bucket
  #   Type: String
  ClusterProfile:
    Type: String
  # FloatingIPAddress:
  #   Type: String
  # RouteTableId:
  #   Type: String
Resources:
  RHELwithHAInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Authentication:
        S3AccessCreds:
          type: S3
          roleName: !Ref ClusterRole
      AWS::CloudFormation::Init:
        configSets:
          install:
            - 'install'
        install:
          packages: 
            yum: 
              pcs: []
              pacemaker: []
              fence-agents-aws: []
    Properties:
      KeyName: !Ref KeyPairName
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref ClusterProfile
      SubnetId: !Ref SubnetId
      ImageId: !Ref ImageId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      UserData: !Base64 
        Fn::Sub:
          - |
            #cloud-config
            runcmd:
              - ['sudo', 'dnf', '-y', 'install', 'wget', 'python3', 'python3-setuptools', 'python3-docutils']
              - ['sudo', 'wget', "https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz", -O, "/tmp/aws-cfn-bootstrap-py3-latest.tar.gz" ]
              - ['sudo', 'wget', '-O', '/tmp/pystache-0.5.4.tar.gz', 'https://files.pythonhosted.org/packages/d6/fd/eb8c212053addd941cc90baac307c00ac246ac3fce7166b86434c6eae963/pystache-0.5.4.tar.gz']
              - ['sudo', 'easy_install-3', '/tmp/pystache-0.5.4.tar.gz']
              - ['sudo', 'easy_install-3', '--script-dir', '/usr/local/bin', '/tmp/aws-cfn-bootstrap-py3-latest.tar.gz']
              - ['sudo', '/usr/local/bin/cfn-init', '-v', '--stack', ${STACKNAME}, '--resource', 'RHELwithHAInstance', '--configsets', 'install', '--region', ${REGION} ]
          - { STACKNAME: !Ref 'AWS::StackName', REGION: !Ref 'AWS::Region' }

